baseURL: http://localhost
title: Test
languageCode: en-us
theme: docsy
modules:
  - path: github.com/google/docsy/dependencies@v0.6.0
    disable: false
enableGitInfo: true
contentDir: content
defaultContentLanguage: en

disableKinds:
  - taxonomy
  - taxonomyTerm

# Highlighting config
pygmentsCodeFences: true
pygmentsUseClasses: false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic: false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle: tango

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
  angledQuotes: false
  latexDashes: true

# Image processing configuration.
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart

pluralizelisttitles: false

markup:
  goldmark:
    renderer:
      unsafe: true  
    extensions:
      table: true
  tableOfContents:
    startLevel: 1

ignoreFiles:
  - grotius_tmp_

